CompApp/urls.py
from django.conf.urls import url

from . import views

app_name = 'CompApp'
urlpatterns = [
    # /comp
    url(r'^$', views.IndexView.as_view(), name='index'),
    # /comp/competition_name
    url(r'^(?P<slug>[\w-]+)/$', views.DetailView.as_view(), name='detail'),
    # /comp/competition_name/event_type/add
    url(r'^(?P<slug>[\w-]+)/(?P<event_type>[\w-]+)/add/$', views.AddEvent.as_view(), name='event'),
    # /comp/competition_name/event_type/delete
    url(r'^(?P<pk>[\w-]+)/(?P<event_type>[\w-]+)/delete/$', views.DeleteEvent.as_view(), name='delete-event'),
]

CompSite/urls.py
from django.conf import settings
from django.conf.urls import url, include
from django.contrib import admin
from . import views

admin.site.site_header = settings.ADMIN_SITE_HEADER

urlpatterns = [
    url(r'^$', views.HomeView.as_view(), name='home'),
    url(r'^admin/', admin.site.urls),
    url(r'^comp/', include('CompApp.urls')),
    url(r'^students/', include('StudentApp.urls')),
    url(r'^results/', include('ResultApp.urls')),
]

if settings.DEBUG:
    import debug_toolbar
    urlpatterns = [
        url(r'^__debug__/', include(debug_toolbar.urls)),
    ] + urlpatterns

ResultApp/urls.py
from django.conf.urls import url

from . import views

app_name = 'ResultApp'
urlpatterns = [
    # /results
    url(r'^$', views.ResultIndexView.as_view(), name='resultindex'),
    # /results/competition_name
    url(r'^(?P<slug>[\w-]+)/$', views.ResultDetailView.as_view(), name='resultdetail'),

    # /results/competition_name/students
    url(r'^(?P<slug>[\w-]+)/students/$', views.StudentResultDetailView.as_view(), name='student-analysis'),
    # /results/competition_name/houses
    url(r'^(?P<slug>[\w-]+)/houses/$', views.HouseResultDetailView.as_view(), name='house-analysis'),

    # /results/event_type/event_slug/createresult
    url(r'^(?P<event_type>[\w-]+)/(?P<event_slug>[\w-]+)/createresult/$', views.EventResultCreate.as_view(), name='event-result'),
    # /results/event_type/event_slug/printresult
    url(r'^(?P<event_type>[\w-]+)/(?P<event_slug>[\w-]+)/printresult/$', views.EventResultPrint.as_view(),
        name='print-event-result'),

]

ResultApp/forms.py
from django.forms import ModelForm, modelformset_factory, DurationField, CharField
from dal import autocomplete
from ResultApp.models import *
from django import forms


class CrossCountryResultForm(ModelForm):
    class Meta:
        model = CrossCountryResult
        fields = ['event', 'student', 'position', 'house_points', ]
        widgets = {
            'student': autocomplete.ModelSelect2(url='StudentApp:student-autocomplete')
        }


class TrackEventResultForm(ModelForm):
    time = CharField(required=False)

    class Meta:
        model = TrackEventResult
        fields = ['event', 'student', 'time', 'house_points', ]
        widgets = {
            'student': autocomplete.ModelSelect2(url='StudentApp:student-autocomplete'),
        }


class FieldEventResultForm(ModelForm):
    class Meta:
        model = FieldEventResult
        fields = ['event', 'student', 'distance', 'house_points', ]
        widgets = {
            'student': autocomplete.ModelSelect2(url='StudentApp:student-autocomplete')
        }


class SwimmingResultForm(ModelForm):
    time = DurationField(required=False)

    class Meta:
        model = SwimmingResult
        fields = ['event', 'student', 'time', 'house_points', ]
        widgets = {
            'student': autocomplete.ModelSelect2(url='StudentApp:student-autocomplete')
        }


class TrackRelayResultForm(ModelForm):
    time = DurationField(required=False)

    class Meta:
        model = TrackRelayResult
        fields = ['house', 'event', 'time', 'house_points', ]


class SwimmingRelayResultForm(ModelForm):
    time = DurationField(required=False)

    class Meta:
        model = SwimmingRelayResult
        fields = ['house', 'event', 'time', 'house_points', ]


CrossCountryResultFormSet = modelformset_factory(CrossCountryResult, form=CrossCountryResultForm, extra=10)
TrackEventResultFormSet = modelformset_factory(TrackEventResult, form=TrackEventResultForm, extra=8)
TrackRelayResultFormSet = modelformset_factory(TrackRelayResult, form=TrackRelayResultForm, extra=3)
FieldEventResultFormSet = modelformset_factory(FieldEventResult, form=FieldEventResultForm, extra=6)
SwimmingResultFormSet = modelformset_factory(SwimmingResult, form=SwimmingResultForm, extra=6)
SwimmingRelayResultFormSet = modelformset_factory(SwimmingRelayResult, form=SwimmingRelayResultForm, extra=3)

ResultApp/views.py
from django.urls import reverse
from django.db.models import Sum
from django.http import Http404
from django.views import generic
from django.shortcuts import render, redirect
from django.utils.safestring import mark_safe
from .forms import *
from StudentApp.models import House
from .models import ResultsModels, RelayResultModels
from CompApp.models import Event, TrackEvent, BOYS, GIRLS, YEAR_7, YEAR_8, YEAR_9, YEAR_10, YEAR_11
import CompApp


class ResultIndexView(generic.ListView):
    template_name = 'ResultApp/resultindex.html'
    model = Competition


class ResultDetailView(generic.DetailView):
    template_name = 'ResultApp/resultdetail.html'
    model = Competition

    def get_context_data(self, **kwargs):
        context = super(ResultDetailView, self).get_context_data(**kwargs)
        competition = self.get_object()
        junior_year_groups = competition.get_junior_year_groups()
        senior_year_groups = competition.get_senior_year_groups()
        houses = House.objects.all()
        junior_boys = self.get_results(competition, junior_year_groups, [BOYS], houses)
        junior_girls = self.get_results(competition, junior_year_groups, [GIRLS], houses)
        senior_boys = self.get_results(
            competition, senior_year_groups, [BOYS], houses
        )
        senior_girls = self.get_results(
            competition, senior_year_groups, [GIRLS], houses
        )
        overall = self.get_results(
            competition,
            junior_year_groups + senior_year_groups,
            [BOYS, GIRLS], houses
        )
        table = [
            ['', 'Roman', 'Trojan', 'Spartan'],
            ['Junior boys', junior_boys['Roman'], junior_boys['Trojan'], junior_boys['Spartan']],
            ['Junior girls', junior_girls['Roman'], junior_girls['Trojan'], junior_girls['Spartan']],
            ['Senior boys', senior_boys['Roman'], senior_boys['Trojan'], senior_boys['Spartan']],
            ['Senior girls', senior_girls['Roman'], senior_girls['Trojan'], senior_girls['Spartan']],
            ['Overall', overall['Roman'], overall['Trojan'], overall['Spartan']],
        ]
        context['table'] = table

        return context

    def get_results(self, competition, years, genders, houses):
        house_totals = {}
        for house in houses:
            house_totals[house.house_name] = 0

        for model in ResultsModels:
            all_results = model.objects.filter(
                event__gender__in=genders, event__competition=competition, event__year_group__in=years
            )
            sum_house_points = all_results.values('student__house__house_name').annotate(total=Sum('house_points'))
            for house_points in sum_house_points:
                house_name = house_points['student__house__house_name']
                house_total = house_points['total']
                house_totals[house_name] += house_total

        for model in RelayResultModels:
            relay_results = model.objects.filter(
                event__gender__in=genders, event__competition=competition, event__year_group__in=years
            )
            sum_house_points = relay_results.values('house__house_name').annotate(total=Sum('house_points'))
            for house_points in sum_house_points:
                house_name = house_points['house__house_name']
                house_total = house_points['total']
                house_totals[house_name] += house_total

        return house_totals


class StudentResultDetailView(generic.DetailView):
    template_name = 'ResultApp/studentanalysis.html'
    model = Competition

    def get_context_data(self, **kwargs):
        context = super(StudentResultDetailView, self).get_context_data(**kwargs)
        competition = self.get_object()
        year_7_boys = self.get_students(competition, [YEAR_7], Student.BOYS)
        year_7_girls = self.get_students(competition, [YEAR_7], Student.GIRLS)
        year_8_boys = self.get_students(competition, [YEAR_8], Student.BOYS)
        year_8_girls = self.get_students(competition, [YEAR_8], Student.GIRLS)
        year_9_boys = self.get_students(competition, [YEAR_9], Student.BOYS)
        year_9_girls = self.get_students(competition, [YEAR_9], Student.GIRLS)
        senior_boys = self.get_students(competition, [YEAR_10, YEAR_11], Student.BOYS)
        senior_girls = self.get_students(competition, [YEAR_10, YEAR_11], Student.GIRLS)

        def div_students(year_gender):
            return mark_safe(''.join(['<div> %s - %s </div>' % student for student in year_gender]))

        table = [
            ['', 'Boys', 'Girls'],
            ['Year 7', div_students(year_7_boys), div_students(year_7_girls)],
            ['Year 8', div_students(year_8_boys), div_students(year_8_girls)],
            ['Year 9', div_students(year_9_boys), div_students(year_9_girls)],
            ['Year 10/11', div_students(senior_boys), div_students(senior_girls)]
        ]
        context['table'] = table
        return context

    def get_students(self, competition, years, gender):
        top_students = {}
        for model in ResultsModels:
            results = model.objects.filter(
                event__year_group__in=years, student__gender=gender, event__competition=competition
            )
            top_results = results.values('student').annotate(
                house_points=Sum('house_points')
            ).order_by('-house_points')
            for top_result in top_results:
                house_points = top_result['house_points']
                student = top_result['student']
                running_total = top_students.get(student, 0)
                running_total+=house_points
                top_students[student]=running_total
        top_five_students = sorted(top_students, key=lambda s: top_students[s], reverse=True)[0:5]
        top_five_student_tuple = [
            (Student.objects.get(id=student_id), top_students[student_id]) for student_id in top_five_students
        ]
        return top_five_student_tuple


class HouseResultDetailView(generic.DetailView):
    template_name = 'ResultApp/houseanalysis.html'
    model = Competition

    def get_context_data(self, **kwargs):
        context = super(HouseResultDetailView, self).get_context_data(**kwargs)
        competition = self.get_object()
        houses = House.objects.all()
        winners = []
        for house in houses:
            student_winners = house.get_student_winners(competition.competition_name)
            winners.append((house, student_winners))
            for student in student_winners:
                generator = student.get_winner_events(competition.competition_name)
                setattr(student, 'winner_events', generator)
        context['student_winners'] = winners
        return context


class EventResultCreate(generic.TemplateView):
    template_name = 'ResultApp/eventresult.html'

    def post(self, request, *args, **kwargs):
        formset_class, model_class = self.get_formset_class(**kwargs)
        event_slug = kwargs['event_slug']
        event = model_class.objects.get(slug=event_slug)
        formset = formset_class(request.POST, request.FILES, initial=[{'id':'event_id'}])
        if formset.is_valid():
            formset.save()
            url = reverse('ResultApp:event-result', kwargs=kwargs)
            return redirect(url)
        else:
            return render(request, self.template_name, {'formset': formset, 'event': event})

    def get(self, request, *args, **kwargs):
        formset_class, model_class = self.get_formset_class(**kwargs)
        event_slug = kwargs['event_slug']
        event = model_class.objects.get(slug=event_slug)
        result_class = formset_class.model
        results_for_event = result_class.objects.filter(event__slug=event_slug)
        formset = formset_class(queryset=results_for_event)

        for form in formset:
            form.fields['event'].initial = event
            if 'time' in form.fields:
                form.fields['time'].widget.attrs['tabindex'] = 2
            if 'distance' in form.fields:
                form.fields['distance'].widget.attrs['tabindex'] = 2
            form.fields['house_points'].widget.attrs['tabindex'] = 3

        return render(request, self.template_name, {'formset': formset, 'event': event})

    def get_formset_class(self, **kwargs):
        event_type = kwargs['event_type']
        my_class = getattr(CompApp.models, event_type)
        if my_class == CrossCountry:
            formset_class = CrossCountryResultFormSet
        elif my_class == TrackEvent:
            formset_class = TrackEventResultFormSet
        elif my_class == FieldEvent:
            formset_class = FieldEventResultFormSet
        elif my_class == TrackRelay:
            formset_class = TrackRelayResultFormSet
        elif my_class == Swimming:
            formset_class = SwimmingResultFormSet
        elif my_class == SwimmingRelay:
            formset_class = SwimmingRelayResultFormSet
        else:
            raise Http404
        return formset_class, my_class


class EventResultPrint(generic.TemplateView):
    template_name = 'ResultApp/printeventresult.html'

    def get(self, request, *args, **kwargs):
        model_class = self.get_model_class(**kwargs)
        event_slug = kwargs['event_slug']
        event = model_class.objects.get(slug=event_slug)
        lane_draw = [1, 8, 2, 7, 3, 6, 4, 5]
        if model_class == CrossCountry:
            event_results = CrossCountryResult.objects.filter(event=event)
            headers = ['House points','', 'Name', 'Position']
        elif model_class == TrackEvent:
            event_results = TrackEventResult.objects.filter(event=event)
            if event.track_choice == TrackEvent.HEATS:
                headers = ['Lane draw', 'House', 'Name', 'Time']
            else:
                headers = ['House points', 'House', 'Name', 'Time']
        elif model_class == FieldEvent:

ResultApp/templates/ResultApp/eventresult.html
{% extends "base.html" %}
{% load static %}
{% block content %}
<p><a class="btn btn-default" href="{% url 'CompApp:detail' event.competition.slug %}">Competition Events</a></p>

    <form action="" method="post">
        {% csrf_token %}
        {{ formset.management_form }}
        {{ formset.non_form_errors }}
        <table>
            {% for form in formset %}
                <tr>
                {% for field in form %}
                    <td>
                    {{ field.errors }}
                    {% if not field.is_hidden %}
                    {{ field.label_tag }}
                    {% endif %}
                    {{ field }}
                    </td>
                {% endfor %}
                </tr>
            {% endfor %}
        </table>
        <input type="submit" value="Submit"/>
    </form>
<br>
<p><a class="btn btn-default" href="{% url 'ResultApp:print-event-result' event.get_event_type event.slug %}">Print</a></p>

{% endblock %}
{% block footer %}
    {{ formset.0.media }}
{% endblock %}

ResultApp/templates/ResultApp/houseanalysis.html
{% extends "base.html" %}
{% load static %}
{% block content %}
<p><a class="btn btn-default" href="{% url 'ResultApp:resultdetail' competition.slug %}">Results Table</a></p>

{% for house in student_winners %}
    <p>{{ house.0 }}</p>
    <ul>
    {% for student in house.1 %}
        <li><strong>{{ student }}</strong> -
            {% for event in student.winner_events %}
            {{ event }},
            {% endfor %}</li>
    {% endfor %}
    </ul>
{% endfor %}

{% endblock %}

ResultApp/templates/ResultApp/printeventresult.html
{% extends "base.html" %}
{% load static duration_tags %}
{% block content %}

<p><a class="btn btn-default" href="{% url 'CompApp:detail' event.competition.slug %}">Competition Events</a></p>
<br>
<h1>{{ event }}</h1>
<br>
<table class="table">
    <tr>
        {% for item in headers %}
            <th>{{ item }}</th>
        {% endfor %}
        <th></th>
    </tr>
    {% for result in event_results%}
    <tr>
        <td>{% if result.event.track_choice == 'Heats' %}
                {% if lane_draw %}
                    {{ lane_draw.pop }}
                {% endif %}
            {% else %}
                {{ result.house_points | floatformat }}
            {% endif %}
        </td>
        <td>{{ result.student.house }}</td>
        <td>{{ result.student }}{{ result.house }}</td>
        <td>{{ result.time | duration }}{{ result.distance | floatformat:2}}</td>
        <td>{% if result.record_check == True %}
            Record Breaker
            {% endif %}</td>
    </tr>
    {% endfor %}
</table>

{% endblock %}

ResultApp/templates/ResultApp/resultdetail.html
{% extends "base.html" %}
{% load static %}
{% block content %}
<p><a class="btn btn-default" href="{% url 'ResultApp:resultindex' %}">Competitions</a></p>

<table class="table">

    {% for row in table %}
        <tr>
        {% for col in row %}
            <td>{{ col }}</td>
        {% endfor %}
        </tr>
    {% endfor %}

</table>

<p><a class="btn btn-default" href="{% url 'ResultApp:student-analysis' competition.slug %}">Student Analysis</a>
<a class="btn btn-default" href="{% url 'ResultApp:house-analysis' competition.slug %}">House Analysis</a></p>

{% endblock %}

ResultApp/templates/ResultApp/resultindex.html
{% extends "base.html" %}
{% load static %}
{% block content %}
<p><a class="btn btn-default" href="{% url 'home' %}">Home</a></p>
<table class="table">
    <tr><td>Competition</td>
        <td>Date</td></tr>

    {% for competition in object_list %}

        <tr><td><a href="{% url 'ResultApp:resultdetail' competition.slug %}">{{competition.competition_name}}</a></td>
            <td>{{ competition.competition_date }}</td></tr>

    {% endfor %}

{% endblock %}

ResultApp/templates/ResultApp/studentanalysis.html
{% extends "base.html" %}
{% load static %}
{% block content %}
<p><a class="btn btn-default" href="{% url 'ResultApp:resultdetail' competition.slug %}">Results Table</a></p>

<table class="table">

    {% for row in table %}
        <tr>
        {% for col in row %}
            <td>{{ col }}</td>
        {% endfor %}
        </tr>
    {% endfor %}

</table>

{% endblock %}