CompApp/urls.py
from django.conf.urls import url

from . import views

app_name = 'CompApp'
urlpatterns = [
    # /comp
    url(r'^$', views.IndexView.as_view(), name='index'),
    # /comp/competition_name
    url(r'^(?P<slug>[\w-]+)/$', views.DetailView.as_view(), name='detail'),
    # /comp/competition_name/event_type/add
    url(r'^(?P<slug>[\w-]+)/(?P<event_type>[\w-]+)/add/$', views.AddEvent.as_view(), name='event'),
    # /comp/competition_name/event_type/delete
    url(r'^(?P<pk>[\w-]+)/(?P<event_type>[\w-]+)/delete/$', views.DeleteEvent.as_view(), name='delete-event'),
]

CompSite/urls.py
from django.conf import settings
from django.conf.urls import url, include
from django.contrib import admin
from . import views

admin.site.site_header = settings.ADMIN_SITE_HEADER

urlpatterns = [
    url(r'^$', views.HomeView.as_view(), name='home'),
    url(r'^admin/', admin.site.urls),
    url(r'^comp/', include('CompApp.urls')),
    url(r'^students/', include('StudentApp.urls')),
    url(r'^results/', include('ResultApp.urls')),
]

if settings.DEBUG:
    import debug_toolbar
    urlpatterns = [
        url(r'^__debug__/', include(debug_toolbar.urls)),
    ] + urlpatterns

ResultApp/urls.py
from django.conf.urls import url

from . import views

app_name = 'ResultApp'
urlpatterns = [
    # /results
    url(r'^$', views.ResultIndexView.as_view(), name='resultindex'),
    # /results/competition_name
    url(r'^(?P<slug>[\w-]+)/$', views.ResultDetailView.as_view(), name='resultdetail'),

    # /results/competition_name/students
    url(r'^(?P<slug>[\w-]+)/students/$', views.StudentResultDetailView.as_view(), name='student-analysis'),
    # /results/competition_name/houses
    url(r'^(?P<slug>[\w-]+)/houses/$', views.HouseResultDetailView.as_view(), name='house-analysis'),

    # /results/event_type/event_slug/createresult
    url(r'^(?P<event_type>[\w-]+)/(?P<event_slug>[\w-]+)/createresult/$', views.EventResultCreate.as_view(), name='event-result'),
    # /results/event_type/event_slug/printresult
    url(r'^(?P<event_type>[\w-]+)/(?P<event_slug>[\w-]+)/printresult/$', views.EventResultPrint.as_view(),
        name='print-event-result'),

]

StudentApp/urls.py
from django.conf.urls import url

from . import views

app_name = 'StudentApp'
urlpatterns = [
    # /students
    url(r'^$', views.SchoolView.as_view(), name='school'),
    # /students/api/studentautocomplete
    url(r'^api/studentautocomplete/$', views.StudentAutoComplete.as_view(), name='student-autocomplete'),
    # /students/schoolname
    url(r'^(?P<slug>[\w-]+)/$', views.HouseView.as_view(), name='house'),
    # /students/schoolname/housename
    url(r'^(?P<slug>[\w-]+)/(?P<house_slug>[\w-]+)/$', views.StudentView.as_view(), name='student'),
]

templates/base.html
<!DOCTYPE html>
<html lang="en">
  <head>
    <meta charset="utf-8">
    <meta http-equiv="X-UA-Compatible" content="IE=edge">
    <meta name="viewport" content="width=device-width, initial-scale=1">
    <!-- The above 3 meta tags *must* come first in the head; any other head content must come *after* these tags -->
    <title>Bootstrap 101 Template</title>

    <!-- Bootstrap -->
    <link rel="stylesheet" href="https://maxcdn.bootstrapcdn.com/bootstrap/3.3.7/css/bootstrap.min.css"
          integrity="sha384-BVYiiSIFeK1dGmJRAkycuHAHRg32OmUcww7on3RYdg4Va+PmSTsz/K68vbdEjh4u" crossorigin="anonymous">

    <!-- HTML5 shim and Respond.js for IE8 support of HTML5 elements and media queries -->
    <!-- WARNING: Respond.js doesn't work if you view the page via file:// -->
    <!--[if lt IE 9]>
      <script src="https://oss.maxcdn.com/html5shiv/3.7.3/html5shiv.min.js"></script>
      <script src="https://oss.maxcdn.com/respond/1.4.2/respond.min.js"></script>
    <![endif]-->
  </head>
  <body>
    {% block content %}
    {% endblock %}
    <!-- jQuery (necessary for Bootstrap's JavaScript plugins) -->
    <script src="https://ajax.googleapis.com/ajax/libs/jquery/1.12.4/jquery.min.js"></script>
    <!-- Include all compiled plugins (below), or include individual files as needed -->
    <script src="https://maxcdn.bootstrapcdn.com/bootstrap/3.3.7/js/bootstrap.min.js"
            integrity="sha384-Tc5IQib027qvyjSMfHjOMaLkfuWVxZxUPnCJA7l2mCWNIpG9mGCD8wGNIcPD7Txa" crossorigin="anonymous"></script>
    {% block footer %}
    {% endblock %}
  </body>
</html>

templates/home.html
{% extends "base.html" %}
{% load static %}
{% block content %}

<p><a class="btn btn-default" href="{% url 'CompApp:index' %}">Competitions</a></p>
<p><a class="btn btn-default" href="{% url 'StudentApp:school' %}">Student Listing</a></p>
<p><a class="btn btn-default" href="{% url 'ResultApp:resultindex' %}">Results</a></p>

{% endblock %}